import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/Banner";
import NavBar from "@/components/nav/navbar";
import Card from "@/components/card/card";
import SectionCards from "../components/card/section-cards";
import { getVideos } from "@/lib/videos";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const disneyVideos = getVideos();

  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar username="Eunji@eunji.net" />
      <Banner
        title="MANDALORIAN"
        subTitle="Space Western"
        imgUrl="/static/mandalorian.webp"
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title="Disney" videos={disneyVideos} size="large" />
        <SectionCards title="Disney" videos={disneyVideos} size="medium" />
      </div>
    </>
  );
}
